// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Location *string `json:"location"`
	Manager  *User   `json:"manager"`
}

type NewItem struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Manager  string `json:"manager"`
}

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
