// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Item struct {
	ID        int32
	Name      string
	Location  sql.NullString
	Counts    int32
	ManagerID int32
}

type User struct {
	ID   int32
	Name string
}
